# This file is generated by `go run ./tools/of-cli docs generate-sdk-python`.
# Do not edit manually.
from __future__ import annotations

import dataclasses
from dataclasses import dataclass
from typing import Any, get_args, get_origin

JsonValue = Any

def serialize_model(value: Any) -> Any:
    if value is None:
        return None
    if dataclasses.is_dataclass(value):
        return {field.name: serialize_model(getattr(value, field.name)) for field in dataclasses.fields(value) if getattr(value, field.name) is not None}
    if isinstance(value, list):
        return [serialize_model(item) for item in value]
    if isinstance(value, dict):
        return {key: serialize_model(item) for key, item in value.items() if item is not None}
    return value

def deserialize_model(model_type: Any, value: Any) -> Any:
    if value is None:
        return None
    origin = get_origin(model_type)
    if origin is list:
        args = get_args(model_type)
        item_type = args[0] if args else Any
        return [deserialize_model(item_type, item) for item in value]
    if origin is dict:
        args = get_args(model_type)
        value_type = args[1] if len(args) == 2 else Any
        return {str(key): deserialize_model(value_type, item) for key, item in value.items()}
    if origin is not None and str(origin).endswith('Union') or origin is getattr(__import__('types'), 'UnionType', object()):
        args = [candidate for candidate in get_args(model_type) if candidate is not type(None)]
        if len(args) == 1:
            return deserialize_model(args[0], value)
        return value
    if model_type in (Any, str, int, float, bool):
        return value
    if isinstance(model_type, type) and dataclasses.is_dataclass(model_type) and isinstance(value, dict):
        payload = {}
        for field in dataclasses.fields(model_type):
            payload[field.name] = deserialize_model(field.type, value.get(field.name))
        return model_type(**payload)
    return value

@dataclass(slots=True)
class AbortTransactionRequest:
    transaction_rid: str | None = None

@dataclass(slots=True)
class AccessPattern:
    id: str | None = None
    kind: str | None = None
    media_set_rid: str | None = None
    params: str | None = None
    persistence: PersistencePolicy | None = None
    ttl_seconds: int | None = None

@dataclass(slots=True)
class AdminGroupsListResponse:
    count: int | None = None
    items: list[GroupResponse] | None = None

@dataclass(slots=True)
class AdminPermissionsListResponse:
    count: int | None = None
    items: list[Permission] | None = None

@dataclass(slots=True)
class AdminPoliciesListResponse:
    count: int | None = None
    items: list[Policy] | None = None

@dataclass(slots=True)
class AdminRolesListResponse:
    count: int | None = None
    items: list[RoleResponse] | None = None

@dataclass(slots=True)
class AdminUsersListResponse:
    count: int | None = None
    items: list[UserResponse] | None = None

@dataclass(slots=True)
class Annotation:
    author_id: Uuid | None = None
    created_at: str | None = None
    geometry_json: str | None = None
    graph_id: Uuid | None = None
    id: Uuid | None = None
    kind: AnnotationKind | None = None
    text: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class ApiError:
    code: str | None = None
    details: dict[str, Any] | None = None
    message: str | None = None
    request_id: str | None = None
    status: int | None = None

@dataclass(slots=True)
class AppBrandingSettings:
    accent_color: str | None = None
    display_name: str | None = None
    favicon_url: str | None = None
    logo_url: str | None = None
    primary_color: str | None = None
    show_powered_by: bool | None = None

@dataclass(slots=True)
class ArrayParams:
    array_sub_type: Field | None = None

@dataclass(slots=True)
class AssignRoleRequest:
    role_id: Uuid | None = None
    user_id: Uuid | None = None

@dataclass(slots=True)
class AssignRoleResponse:
    pass

@dataclass(slots=True)
class AuditEvent:
    action: str | None = None
    actor_id: str | None = None
    categories: list[str] | None = None
    correlation_id: str | None = None
    event_id: str | None = None
    ip: str | None = None
    kind: str | None = None
    markings_at_event: list[str] | None = None
    occurred_at: str | None = None
    payload: str | None = None
    project_rid: str | None = None
    request_id: str | None = None
    resource_rid: str | None = None
    source_service: str | None = None
    user_agent: str | None = None

@dataclass(slots=True)
class AuditEventExport:
    event_ndjson: str | None = None

@dataclass(slots=True)
class BindDatasetRequest:
    dataset_branch: str | None = None
    dataset_id: Uuid | None = None
    dataset_version: int | None = None
    default_marking: str | None = None
    object_type_id: Uuid | None = None
    preview_limit: int | None = None
    primary_key_column: str | None = None
    property_mapping: list[ObjectTypeBindingPropertyMapping] | None = None
    sync_mode: ObjectTypeBindingSyncMode | None = None

@dataclass(slots=True)
class Branch:
    created_at: str | None = None
    created_from_transaction_rid: str | None = None
    dataset_rid: str | None = None
    fallback_chain: list[str] | None = None
    has_open_transaction: bool | None = None
    head_transaction_rid: str | None = None
    is_root: bool | None = None
    labels: dict[str, str] | None = None
    last_activity_at: str | None = None
    name: str | None = None
    parent_branch_rid: str | None = None
    rid: str | None = None

@dataclass(slots=True)
class Build:
    build_branch: str | None = None
    error_message: str | None = None
    finished_at: str | None = None
    force_build: bool | None = None
    job_spec_fallback: list[str] | None = None
    pipeline_rid: str | None = None
    queued_at: str | None = None
    requested_by: str | None = None
    rid: str | None = None
    started_at: str | None = None
    state: BuildState | None = None
    trigger_kind: str | None = None

@dataclass(slots=True)
class CancelIngestJobRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class CancelIngestJobResponse:
    pass

@dataclass(slots=True)
class Cell:
    cell_type: str | None = None
    created_at: str | None = None
    execution_count: int | None = None
    id: str | None = None
    kernel: str | None = None
    last_output: Value | None = None
    notebook_id: str | None = None
    position: int | None = None
    source: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class CellOutput:
    content: Value | None = None
    execution_count: int | None = None
    output_type: str | None = None

@dataclass(slots=True)
class CentralityRequest:
    branch_context: str | None = None
    measures: list[CentralityMeasure] | None = None
    object_refs: list[ObjectRef] | None = None

@dataclass(slots=True)
class CentralityResponse:
    scores: list[CentralityScore] | None = None

@dataclass(slots=True)
class CentralityScore:
    measure: CentralityMeasure | None = None
    ref: ObjectRef | None = None
    value: float | None = None

@dataclass(slots=True)
class Column:
    data_type: str | None = None
    name: str | None = None

@dataclass(slots=True)
class ColumnMeta:
    data_type: str | None = None
    name: str | None = None

@dataclass(slots=True)
class CommitTransactionRequest:
    transaction_rid: str | None = None

@dataclass(slots=True)
class CompileTransformRequest:
    config_json: str | None = None
    language: TransformLanguage | None = None
    source: str | None = None

@dataclass(slots=True)
class CompileTransformResponse:
    compiled: bool | None = None
    compiled_form: str | None = None
    deferred: bool | None = None
    diagnostics: list[ValidationDiagnostic] | None = None

@dataclass(slots=True)
class CompoundTrigger:
    pass

@dataclass(slots=True)
class Connection:
    config: dict[str, str] | None = None
    connector_type: ConnectorType | None = None
    created_at: str | None = None
    id: Uuid | None = None
    last_sync_at: str | None = None
    name: str | None = None
    status: ConnectionStatus | None = None

@dataclass(slots=True)
class ControlPanelSettings:
    allow_self_signup: bool | None = None
    allowed_email_domains: list[str] | None = None
    announcement_banner: str | None = None
    default_app_branding: AppBrandingSettings | None = None
    default_region: str | None = None
    deployment_mode: str | None = None
    docs_url: str | None = None
    maintenance_mode: bool | None = None
    platform_name: str | None = None
    release_channel: str | None = None
    restricted_operations: list[str] | None = None
    status_page_url: str | None = None
    support_email: str | None = None
    updated_at: str | None = None
    updated_by: str | None = None

@dataclass(slots=True)
class Cost:
    budget_exceeded: bool | None = None
    cpu_seconds: float | None = None
    indices_hit: list[str] | None = None
    rows_scanned: int | None = None

@dataclass(slots=True)
class CreateAnnotationRequest:
    geometry_json: str | None = None
    graph_id: Uuid | None = None
    kind: AnnotationKind | None = None
    text: str | None = None

@dataclass(slots=True)
class CreateBranchRequest:
    as_root: Empty | None = None
    dataset_rid: str | None = None
    from_branch: str | None = None
    from_transaction_rid: str | None = None
    name: str | None = None

@dataclass(slots=True)
class CreateCellRequest:
    cell_type: str | None = None
    kernel: str | None = None
    notebook_id: str | None = None
    position: int | None = None
    source: str | None = None

@dataclass(slots=True)
class CreateConnectionRequest:
    config: dict[str, str] | None = None
    connector_type: ConnectorType | None = None
    name: str | None = None

@dataclass(slots=True)
class CreateDatasetRequest:
    description: str | None = None
    format: DatasetFormat | None = None
    name: str | None = None
    tags: list[str] | None = None

@dataclass(slots=True)
class CreateDerivedPropertyBindingRequest:
    description: str | None = None
    display_name: str | None = None
    function_rid: str | None = None
    object_type_id: Uuid | None = None
    property_name: str | None = None
    return_type: ParamType | None = None

@dataclass(slots=True)
class CreateGraphRequest:
    branch_context: str | None = None
    description: str | None = None
    markings: list[str] | None = None
    model_rid: str | None = None
    organizations: list[str] | None = None
    project_id: Uuid | None = None
    seed_object_refs: list[str] | None = None
    title: str | None = None

@dataclass(slots=True)
class CreateGraphVersionRequest:
    changelog: str | None = None
    graph_id: Uuid | None = None

@dataclass(slots=True)
class CreateGroupRequest:
    description: str | None = None
    name: str | None = None
    role_ids: list[str] | None = None

@dataclass(slots=True)
class CreateLinkTypeRequest:
    cardinality: str | None = None
    description: str | None = None
    display_name: str | None = None
    name: str | None = None
    source_type_id: Uuid | None = None
    target_type_id: Uuid | None = None

@dataclass(slots=True)
class CreateMediaSetRequest:
    allowed_mime_types: list[str] | None = None
    markings: list[str] | None = None
    name: str | None = None
    project_rid: str | None = None
    retention_seconds: int | None = None
    schema: MediaSetSchema | None = None
    source_rid: str | None = None
    transaction_policy: TransactionPolicy | None = None
    virtual: bool | None = None

@dataclass(slots=True)
class CreateNotebookRequest:
    default_kernel: str | None = None
    description: str | None = None
    name: str | None = None

@dataclass(slots=True)
class CreateObjectRequest:
    marking: str | None = None
    object_type_id: str | None = None
    properties: Struct | None = None

@dataclass(slots=True)
class CreateObjectTypeRequest:
    color: str | None = None
    description: str | None = None
    display_name: str | None = None
    icon: str | None = None
    name: str | None = None
    primary_key_property: str | None = None

@dataclass(slots=True)
class CreatePermissionRequest:
    action: str | None = None
    description: str | None = None
    resource: str | None = None

@dataclass(slots=True)
class CreatePipelineRequest:
    description: str | None = None
    name: str | None = None
    nodes: list[PipelineNode] | None = None

@dataclass(slots=True)
class CreateProductRequest:
    author: str | None = None
    description: str | None = None
    name: str | None = None
    resources: list[ResourceRef] | None = None

@dataclass(slots=True)
class CreatePropertyRequest:
    default_value_json: str | None = None
    description: str | None = None
    display_name: str | None = None
    name: str | None = None
    object_type_id: Uuid | None = None
    property_type: str | None = None
    required: bool | None = None
    unique_constraint: bool | None = None
    validation_rules_json: str | None = None

@dataclass(slots=True)
class CreateRoleRequest:
    description: str | None = None
    name: str | None = None
    permission_ids: list[str] | None = None

@dataclass(slots=True)
class CreateScenarioRequest:
    branch_context: str | None = None
    description: str | None = None
    edits: list[StagedEdit] | None = None
    graph_id: Uuid | None = None
    name: str | None = None

@dataclass(slots=True)
class CreateScheduleRequest:
    description: str | None = None
    name: str | None = None
    paused: bool | None = None
    project_rid: str | None = None
    target: ScheduleTarget | None = None
    trigger: Trigger | None = None

@dataclass(slots=True)
class CreateSearchAroundRequest:
    description: str | None = None
    parameters: list[SearchAroundParameter] | None = None
    project_id: Uuid | None = None
    starting_object_type_id: Uuid | None = None
    steps: list[SearchAroundStep] | None = None
    title: str | None = None

@dataclass(slots=True)
class CreateSessionRequest:
    kernel: str | None = None
    notebook_id: str | None = None

@dataclass(slots=True)
class CsvOptions:
    charset: str | None = None
    date_format: str | None = None
    delimiter: str | None = None
    escape: str | None = None
    header: bool | None = None
    null_value: str | None = None
    quote: str | None = None
    timestamp_format: str | None = None

@dataclass(slots=True)
class CustomMetadata:
    csv: CsvOptions | None = None

@dataclass(slots=True)
class Dataset:
    created_at: str | None = None
    current_version: int | None = None
    description: str | None = None
    format: DatasetFormat | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    row_count: int | None = None
    schema: Schema | None = None
    size_bytes: int | None = None
    storage_path: str | None = None
    tags: list[str] | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class DatasetBuildTarget:
    build_branch: str | None = None
    dataset_rid: str | None = None
    force_build: bool | None = None

@dataclass(slots=True)
class DatasetVersion:
    created_at: str | None = None
    message: str | None = None
    row_count: int | None = None
    size_bytes: int | None = None
    version: int | None = None

@dataclass(slots=True)
class DecimalParams:
    precision: int | None = None
    scale: int | None = None

@dataclass(slots=True)
class DeleteAnnotationRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteAnnotationResponse:
    deleted: bool | None = None

@dataclass(slots=True)
class DeleteConnectionRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteConnectionResponse:
    pass

@dataclass(slots=True)
class DeleteDatasetRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteDatasetResponse:
    pass

@dataclass(slots=True)
class DeleteDerivedPropertyBindingRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteDerivedPropertyBindingResponse:
    deleted: bool | None = None

@dataclass(slots=True)
class DeleteGraphRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteGraphResponse:
    deleted: bool | None = None

@dataclass(slots=True)
class DeleteLinkTypeRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteLinkTypeResponse:
    pass

@dataclass(slots=True)
class DeleteMediaItemRequest:
    rid: str | None = None

@dataclass(slots=True)
class DeleteMediaItemResponse:
    pass

@dataclass(slots=True)
class DeleteMediaSetRequest:
    rid: str | None = None

@dataclass(slots=True)
class DeleteMediaSetResponse:
    pass

@dataclass(slots=True)
class DeleteNotebookRequest:
    id: str | None = None

@dataclass(slots=True)
class DeleteObjectRequest:
    object_type_id: str | None = None
    primary_key: str | None = None

@dataclass(slots=True)
class DeleteObjectResponse:
    cascaded_links: int | None = None
    deleted: bool | None = None

@dataclass(slots=True)
class DeleteObjectTypeRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteObjectTypeResponse:
    pass

@dataclass(slots=True)
class DeletePipelineRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeletePipelineResponse:
    pass

@dataclass(slots=True)
class DeleteSavedQueryRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteSavedQueryResponse:
    pass

@dataclass(slots=True)
class DeleteScenarioRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteScenarioResponse:
    deleted: bool | None = None

@dataclass(slots=True)
class DeleteScheduleRequest:
    rid: str | None = None

@dataclass(slots=True)
class DeleteScheduleResponse:
    pass

@dataclass(slots=True)
class DeleteSearchAroundRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DeleteSearchAroundResponse:
    deleted: bool | None = None

@dataclass(slots=True)
class DerivedPropertyBinding:
    created_at: str | None = None
    description: str | None = None
    display_name: str | None = None
    function_rid: str | None = None
    id: Uuid | None = None
    object_type_id: Uuid | None = None
    owner_id: Uuid | None = None
    property_name: str | None = None
    return_type: ParamType | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class DiffScenarioRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class DisableModelRequest:
    rid: Uuid | None = None

@dataclass(slots=True)
class DropSessionRequest:
    session_id: str | None = None

@dataclass(slots=True)
class DropSessionResponse:
    pass

@dataclass(slots=True)
class EnableModelRequest:
    rid: Uuid | None = None

@dataclass(slots=True)
class EnsureSessionRequest:
    session_id: str | None = None

@dataclass(slots=True)
class EnsureSessionResponse:
    pass

@dataclass(slots=True)
class ErrorDetail:
    code: str | None = None
    message: str | None = None
    metadata: dict[str, str] | None = None

@dataclass(slots=True)
class EvaluatePolicyRequest:
    action: str | None = None
    resource: str | None = None
    resource_attributes: dict[str, Any] | None = None

@dataclass(slots=True)
class EventMessage:
    headers: dict[str, str] | None = None
    payload: str | None = None
    schema_id: str | None = None
    topic: str | None = None

@dataclass(slots=True)
class EventTrigger:
    branch_filter: list[str] | None = None
    target_rid: str | None = None
    type: EventType | None = None

@dataclass(slots=True)
class ExecuteCellRequest:
    cell_id: str | None = None

@dataclass(slots=True)
class ExecuteInlineFunctionRequest:
    input_json: str | None = None
    source: str | None = None
    timeout_seconds: int | None = None

@dataclass(slots=True)
class ExecuteInlineFunctionResponse:
    error: str | None = None
    result_json: str | None = None
    stderr: str | None = None
    stdout: str | None = None

@dataclass(slots=True)
class ExecuteNotebookCellRequest:
    notebook_id: str | None = None
    session_id: str | None = None
    source: str | None = None
    timeout_seconds: int | None = None
    workspace_dir: str | None = None

@dataclass(slots=True)
class ExecuteNotebookCellResponse:
    content_json: str | None = None
    error: str | None = None
    output_type: str | None = None
    stdout: str | None = None

@dataclass(slots=True)
class ExecutePipelineTransformRequest:
    config_json: str | None = None
    input_dataset_ids: list[str] | None = None
    output_dataset_id: str | None = None
    prepared_inputs_json: str | None = None
    source: str | None = None
    timeout_seconds: int | None = None

@dataclass(slots=True)
class ExecutePipelineTransformResponse:
    rows_affected: int | None = None
    rows_affected_set: bool | None = None

@dataclass(slots=True)
class ExecuteQueryRequest:
    limit: int | None = None
    offset: int | None = None
    parameters: dict[str, str] | None = None
    sql: str | None = None

@dataclass(slots=True)
class ExecuteSearchAroundRequest:
    inline: InlineSearchAround | None = None
    saved_search_around_id: Uuid | None = None

@dataclass(slots=True)
class ExecuteSearchAroundResponse:
    cost: Cost | None = None
    groups: list[ResultGroup] | None = None

@dataclass(slots=True)
class ExpandNeighborsRequest:
    branch_context: str | None = None
    cursor: str | None = None
    direction: Direction | None = None
    filters: list[SearchAroundFilter] | None = None
    limit: int | None = None
    link_type_id: Uuid | None = None
    object_id: str | None = None
    object_type_id: Uuid | None = None

@dataclass(slots=True)
class ExpandNeighborsResponse:
    hidden_count: int | None = None
    items: list[ObjectRef] | None = None
    next_cursor: str | None = None
    total: int | None = None
    total_is_estimate: bool | None = None

@dataclass(slots=True)
class ExplainQueryRequest:
    sql: str | None = None

@dataclass(slots=True)
class ExplainQueryResponse:
    logical_plan: str | None = None
    physical_plan: str | None = None

@dataclass(slots=True)
class ExportEventsRequest:
    action: str | None = None
    actor_id: str | None = None
    from: str | None = None
    resource_rid: str | None = None
    to: str | None = None

@dataclass(slots=True)
class ExternalConfig:
    compute_profile_id: str | None = None
    source_id: Uuid | None = None
    source_system: str | None = None

@dataclass(slots=True)
class Field:
    array: ArrayParams | None = None
    decimal: DecimalParams | None = None
    field_type: FieldType | None = None
    map: MapParams | None = None
    metadata: dict[str, str] | None = None
    name: str | None = None
    nullable: bool | None = None
    struct: StructParams | None = None

@dataclass(slots=True)
class FilesystemBreadcrumb:
    name: str | None = None
    path: str | None = None

@dataclass(slots=True)
class FilesystemEntry:
    content_type: str | None = None
    entry_type: str | None = None
    last_modified: str | None = None
    metadata: dict[str, Any] | None = None
    name: str | None = None
    path: str | None = None
    size_bytes: int | None = None
    storage_path: str | None = None

@dataclass(slots=True)
class FilesystemListResponse:
    active_branch: str | None = None
    breadcrumbs: list[FilesystemBreadcrumb] | None = None
    current_version: int | None = None
    dataset_id: str | None = None
    entries: list[FilesystemEntry] | None = None
    items: list[FilesystemEntry] | None = None
    requested_path: str | None = None
    root: str | None = None
    sections: FilesystemSections | None = None

@dataclass(slots=True)
class FilesystemSections:
    branches: int | None = None
    versions: int | None = None
    views: int | None = None

@dataclass(slots=True)
class FindPathsRequest:
    branch_context: str | None = None
    end: ObjectRef | None = None
    k: int | None = None
    max_hops: int | None = None
    start: ObjectRef | None = None

@dataclass(slots=True)
class FindPathsResponse:
    paths: list[Path] | None = None

@dataclass(slots=True)
class ForkGraphRequest:
    id: Uuid | None = None
    new_title: str | None = None

@dataclass(slots=True)
class GeneratePresignedDownloadUrlRequest:
    expires_in_seconds: int | None = None
    media_item_rid: str | None = None

@dataclass(slots=True)
class GeneratePresignedUploadUrlRequest:
    branch: str | None = None
    expires_in_seconds: int | None = None
    media_set_rid: str | None = None
    mime_type: str | None = None
    path: str | None = None
    transaction_rid: str | None = None

@dataclass(slots=True)
class GetDatasetLineageRequest:
    dataset_id: Uuid | None = None

@dataclass(slots=True)
class GetDatasetRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetFullLineageRequest:
    pass

@dataclass(slots=True)
class GetGraphRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetGraphVersionRequest:
    graph_id: Uuid | None = None
    version: int | None = None

@dataclass(slots=True)
class GetIngestJobRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetMeRequest:
    pass

@dataclass(slots=True)
class GetMediaItemRequest:
    rid: str | None = None

@dataclass(slots=True)
class GetMediaSetRequest:
    rid: str | None = None

@dataclass(slots=True)
class GetModelRequest:
    rid: Uuid | None = None

@dataclass(slots=True)
class GetNotebookRequest:
    id: str | None = None

@dataclass(slots=True)
class GetObjectRequest:
    object_type_id: str | None = None
    primary_key: str | None = None

@dataclass(slots=True)
class GetObjectTypeRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetPipelineRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetProductRequest:
    rid: str | None = None

@dataclass(slots=True)
class GetRunRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetScenarioRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetScheduleRequest:
    rid: str | None = None

@dataclass(slots=True)
class GetScheduleRunRequest:
    rid: str | None = None

@dataclass(slots=True)
class GetSearchAroundRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class GetVersionsRequest:
    dataset_id: Uuid | None = None

@dataclass(slots=True)
class GetVersionsResponse:
    versions: list[DatasetVersion] | None = None

@dataclass(slots=True)
class Graph:
    branch_context: str | None = None
    created_at: str | None = None
    description: str | None = None
    id: Uuid | None = None
    layer_configuration_json: str | None = None
    layout_state_json: str | None = None
    markings: list[str] | None = None
    model_rid: str | None = None
    organizations: list[str] | None = None
    owner_id: Uuid | None = None
    project_id: Uuid | None = None
    rid: str | None = None
    seed_object_refs: list[str] | None = None
    timeline_state_json: str | None = None
    title: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class GraphVersion:
    author_id: Uuid | None = None
    changelog: str | None = None
    created_at: str | None = None
    graph_id: Uuid | None = None
    id: Uuid | None = None
    snapshot_json: str | None = None
    version: int | None = None

@dataclass(slots=True)
class GroupResponse:
    created_at: str | None = None
    description: str | None = None
    id: str | None = None
    member_count: int | None = None
    name: str | None = None
    role_ids: list[str] | None = None
    roles: list[str] | None = None

@dataclass(slots=True)
class HealthCheckRequest:
    service: str | None = None

@dataclass(slots=True)
class HealthCheckResponse:
    pass

@dataclass(slots=True)
class HealthCheckTarget:
    check_rid: str | None = None

@dataclass(slots=True)
class HistogramBucket:
    count: int | None = None
    value_json: str | None = None

@dataclass(slots=True)
class HistogramFacet:
    buckets: list[HistogramBucket] | None = None
    n: int | None = None
    numeric: NumericSummary | None = None
    object_type_id: Uuid | None = None
    property: str | None = None
    uniq: int | None = None

@dataclass(slots=True)
class HistogramRequest:
    branch_context: str | None = None
    object_refs: list[ObjectRef] | None = None
    properties: list[str] | None = None

@dataclass(slots=True)
class HistogramResponse:
    facets: list[HistogramFacet] | None = None

@dataclass(slots=True)
class IncrementalConfig:
    allowed_transaction_types: str | None = None
    replay_on_deploy: bool | None = None
    watermark_columns: list[str] | None = None

@dataclass(slots=True)
class InferSchemaRequest:
    connection_id: Uuid | None = None
    table_name: str | None = None

@dataclass(slots=True)
class InferSchemaResponse:
    columns: list[InferredColumn] | None = None

@dataclass(slots=True)
class InferredColumn:
    inferred_type: str | None = None
    name: str | None = None
    nullable: bool | None = None
    source_type: str | None = None

@dataclass(slots=True)
class IngestJob:
    attempts: int | None = None
    completed_at: str | None = None
    connection_id: Uuid | None = None
    created_at: str | None = None
    error: str | None = None
    id: Uuid | None = None
    max_attempts: int | None = None
    next_retry_at: str | None = None
    rows_synced: int | None = None
    scheduled_at: str | None = None
    started_at: str | None = None
    status: IngestJobStatus | None = None
    table_name: str | None = None
    target_dataset_id: Uuid | None = None

@dataclass(slots=True)
class InlineSearchAround:
    parameters: list[SearchAroundParameter] | None = None
    starting_object_type_id: Uuid | None = None
    steps: list[SearchAroundStep] | None = None

@dataclass(slots=True)
class InputSpec:
    dataset_rid: str | None = None
    fallback_chain: list[str] | None = None
    require_fresh: bool | None = None
    view_filter: list[str] | None = None

@dataclass(slots=True)
class InstallProductRequest:
    parameter_map: str | None = None
    product_rid: str | None = None
    target_workspace_rid: str | None = None
    version: str | None = None

@dataclass(slots=True)
class Installation:
    failure_reason: str | None = None
    installed_at: str | None = None
    product_rid: str | None = None
    resource_mappings: list[ResourceMapping] | None = None
    rid: str | None = None
    status: InstallationStatus | None = None
    target_workspace_rid: str | None = None
    updated_at: str | None = None
    version: str | None = None

@dataclass(slots=True)
class InvokeRequest:
    max_tokens: int | None = None
    messages: list[Message] | None = None
    model_rid: Uuid | None = None
    stream: bool | None = None
    temperature: float | None = None
    tools: list[Tool] | None = None

@dataclass(slots=True)
class InvokeResponse:
    cost_usd: float | None = None
    messages: list[Message] | None = None
    model_rid: str | None = None
    usage: Usage | None = None

@dataclass(slots=True)
class InvokeStreamChunk:
    delta: str | None = None
    done: bool | None = None
    usage: Usage | None = None

@dataclass(slots=True)
class Job:
    attempt: int | None = None
    build_rid: str | None = None
    failure_reason: str | None = None
    job_spec_rid: str | None = None
    output_content_hash: str | None = None
    output_transaction_rids: list[str] | None = None
    rid: str | None = None
    stale_skipped: bool | None = None
    state: JobState | None = None
    state_changed_at: str | None = None

@dataclass(slots=True)
class JobSpec:
    branch_name: str | None = None
    content_hash: str | None = None
    inputs: list[InputSpec] | None = None
    logic_kind: str | None = None
    logic_payload: Struct | None = None
    output_dataset_rids: list[str] | None = None
    pipeline_rid: str | None = None
    rid: str | None = None

@dataclass(slots=True)
class LineageEdge:
    node_id: str | None = None
    pipeline_id: Uuid | None = None
    source_dataset_id: Uuid | None = None
    target_dataset_id: Uuid | None = None

@dataclass(slots=True)
class LineageGraph:
    edges: list[LineageEdge] | None = None
    nodes: list[LineageNode] | None = None

@dataclass(slots=True)
class LineageNode:
    dataset_id: Uuid | None = None

@dataclass(slots=True)
class LinkSummaryEntry:
    count: int | None = None
    count_is_estimate: bool | None = None
    direction: Direction | None = None
    display_name: str | None = None
    link_type_id: Uuid | None = None
    target_object_type_id: Uuid | None = None

@dataclass(slots=True)
class LinkSummaryRequest:
    branch_context: str | None = None
    object_id: str | None = None
    object_type_id: Uuid | None = None

@dataclass(slots=True)
class LinkSummaryResponse:
    entries: list[LinkSummaryEntry] | None = None

@dataclass(slots=True)
class LinkType:
    cardinality: str | None = None
    created_at: str | None = None
    description: str | None = None
    display_name: str | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    source_type_id: Uuid | None = None
    target_type_id: Uuid | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class LinkedEdge:
    depth: int | None = None
    direction: LinkDirection | None = None
    link_id: str | None = None
    link_type_api_name: str | None = None
    properties: Struct | None = None
    source_object_id: str | None = None
    target_object_id: str | None = None

@dataclass(slots=True)
class ListAccessPatternsRequest:
    media_set_rid: str | None = None
    pagination: PageRequest | None = None

@dataclass(slots=True)
class ListAccessPatternsResponse:
    pagination: PageResponse | None = None
    patterns: list[AccessPattern] | None = None

@dataclass(slots=True)
class ListAnnotationsRequest:
    graph_id: Uuid | None = None

@dataclass(slots=True)
class ListAnnotationsResponse:
    items: list[Annotation] | None = None

@dataclass(slots=True)
class ListConnectionsRequest:
    pagination: PageRequest | None = None

@dataclass(slots=True)
class ListConnectionsResponse:
    connections: list[Connection] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListDatasetsRequest:
    pagination: PageRequest | None = None
    search: str | None = None
    tags: list[str] | None = None

@dataclass(slots=True)
class ListDatasetsResponse:
    datasets: list[Dataset] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListDerivedPropertyBindingsRequest:
    object_type_id: Uuid | None = None

@dataclass(slots=True)
class ListDerivedPropertyBindingsResponse:
    items: list[DerivedPropertyBinding] | None = None

@dataclass(slots=True)
class ListGraphVersionsRequest:
    graph_id: Uuid | None = None
    pagination: PageRequest | None = None

@dataclass(slots=True)
class ListGraphVersionsResponse:
    items: list[GraphVersion] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListGraphsRequest:
    pagination: PageRequest | None = None
    project_id: Uuid | None = None
    search: str | None = None

@dataclass(slots=True)
class ListGraphsResponse:
    items: list[Graph] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListIngestJobsRequest:
    connection_id: Uuid | None = None
    pagination: PageRequest | None = None

@dataclass(slots=True)
class ListIngestJobsResponse:
    jobs: list[IngestJob] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListInstallationsRequest:
    limit: int | None = None
    offset: int | None = None
    product_rid: str | None = None
    target_workspace_rid: str | None = None

@dataclass(slots=True)
class ListInstallationsResponse:
    items: list[Installation] | None = None
    total: int | None = None

@dataclass(slots=True)
class ListLinkTypesRequest:
    object_type_id: Uuid | None = None
    pagination: PageRequest | None = None

@dataclass(slots=True)
class ListLinkTypesResponse:
    link_types: list[LinkType] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListMediaItemsRequest:
    branch: str | None = None
    media_set_rid: str | None = None
    pagination: PageRequest | None = None
    path_prefix: str | None = None

@dataclass(slots=True)
class ListMediaItemsResponse:
    items: list[MediaItem] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListMediaSetsRequest:
    pagination: PageRequest | None = None
    project_rid: str | None = None

@dataclass(slots=True)
class ListMediaSetsResponse:
    media_sets: list[MediaSet] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListModelsRequest:
    only_enabled: bool | None = None
    provider: Provider | None = None

@dataclass(slots=True)
class ListModelsResponse:
    data: list[Model] | None = None

@dataclass(slots=True)
class ListNotebooksRequest:
    page: int | None = None
    per_page: int | None = None
    search: str | None = None

@dataclass(slots=True)
class ListNotebooksResponse:
    data: list[Notebook] | None = None
    page: int | None = None
    per_page: int | None = None
    total: int | None = None

@dataclass(slots=True)
class ListObjectTypesRequest:
    pagination: PageRequest | None = None
    search: str | None = None

@dataclass(slots=True)
class ListObjectTypesResponse:
    object_types: list[ObjectType] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListObjectsRequest:
    cursor: str | None = None
    filters: list[PropertyFilter] | None = None
    object_type_id: str | None = None
    page_size: int | None = None
    sort: list[PropertySort] | None = None

@dataclass(slots=True)
class ListObjectsResponse:
    next_cursor: str | None = None
    objects: list[ObjectInstance] | None = None
    total: int | None = None

@dataclass(slots=True)
class ListPipelinesRequest:
    pagination: PageRequest | None = None
    search: str | None = None

@dataclass(slots=True)
class ListPipelinesResponse:
    pagination: PageResponse | None = None
    pipelines: list[Pipeline] | None = None

@dataclass(slots=True)
class ListProductsRequest:
    limit: int | None = None
    offset: int | None = None
    status: ProductStatus | None = None

@dataclass(slots=True)
class ListProductsResponse:
    items: list[Product] | None = None
    total: int | None = None

@dataclass(slots=True)
class ListPropertiesRequest:
    object_type_id: Uuid | None = None

@dataclass(slots=True)
class ListPropertiesResponse:
    properties: list[Property] | None = None

@dataclass(slots=True)
class ListRolesRequest:
    pass

@dataclass(slots=True)
class ListRolesResponse:
    roles: list[Role] | None = None

@dataclass(slots=True)
class ListRunsRequest:
    pagination: PageRequest | None = None
    pipeline_id: Uuid | None = None

@dataclass(slots=True)
class ListRunsResponse:
    pagination: PageResponse | None = None
    runs: list[PipelineRun] | None = None

@dataclass(slots=True)
class ListSavedQueriesRequest:
    pagination: PageRequest | None = None
    search: str | None = None

@dataclass(slots=True)
class ListSavedQueriesResponse:
    pagination: PageResponse | None = None
    queries: list[SavedQuery] | None = None

@dataclass(slots=True)
class ListScenariosRequest:
    graph_id: Uuid | None = None
    pagination: PageRequest | None = None

@dataclass(slots=True)
class ListScenariosResponse:
    items: list[Scenario] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListScheduleRunsRequest:
    limit: int | None = None
    offset: int | None = None
    outcome: RunOutcome | None = None
    schedule_rid: str | None = None

@dataclass(slots=True)
class ListScheduleRunsResponse:
    runs: list[ScheduleRun] | None = None
    total: int | None = None

@dataclass(slots=True)
class ListSchedulesRequest:
    include_paused: bool | None = None
    owner: str | None = None
    pagination: PageRequest | None = None
    project_rid: str | None = None
    query: str | None = None

@dataclass(slots=True)
class ListSchedulesResponse:
    pagination: PageResponse | None = None
    schedules: list[Schedule] | None = None

@dataclass(slots=True)
class ListSearchAroundsRequest:
    pagination: PageRequest | None = None
    project_id: Uuid | None = None
    search: str | None = None
    starting_object_type_id: Uuid | None = None

@dataclass(slots=True)
class ListSearchAroundsResponse:
    items: list[SearchAround] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class ListSessionsRequest:
    notebook_id: str | None = None

@dataclass(slots=True)
class ListSessionsResponse:
    data: list[Session] | None = None

@dataclass(slots=True)
class LoginRequest:
    email: str | None = None
    password: str | None = None

@dataclass(slots=True)
class MapParams:
    map_key_type: Field | None = None
    map_value_type: Field | None = None

@dataclass(slots=True)
class MaterializeBindingRequest:
    binding_id: Uuid | None = None
    dataset_branch: str | None = None
    dataset_version: int | None = None
    dry_run: bool | None = None
    limit: int | None = None
    object_type_id: Uuid | None = None

@dataclass(slots=True)
class MaterializeBindingResponse:
    binding_id: Uuid | None = None
    dry_run: bool | None = None
    error_details_json: list[str] | None = None
    errors: int | None = None
    inserted: int | None = None
    rows_read: int | None = None
    skipped: int | None = None
    status: str | None = None
    updated: int | None = None

@dataclass(slots=True)
class MediaItem:
    branch: str | None = None
    created_at: str | None = None
    deduplicated_from: str | None = None
    media_set_rid: str | None = None
    metadata: str | None = None
    mime_type: str | None = None
    path: str | None = None
    rid: str | None = None
    sha256: str | None = None
    size_bytes: int | None = None
    transaction_rid: str | None = None

@dataclass(slots=True)
class MediaSet:
    allowed_mime_types: list[str] | None = None
    created_at: str | None = None
    created_by: str | None = None
    markings: list[str] | None = None
    name: str | None = None
    project_rid: str | None = None
    retention_seconds: int | None = None
    rid: str | None = None
    schema: MediaSetSchema | None = None
    source_rid: str | None = None
    transaction_policy: TransactionPolicy | None = None
    virtual: bool | None = None

@dataclass(slots=True)
class MergeBranchRequest:
    dataset_rid: str | None = None
    source_branch: str | None = None
    target_branch: str | None = None

@dataclass(slots=True)
class MergeBranchResponse:
    already_merged: bool | None = None
    branch: Branch | None = None
    fast_forwarded: bool | None = None
    new_head_transaction_rid: str | None = None
    previous_head_transaction_rid: str | None = None

@dataclass(slots=True)
class Message:
    content: str | None = None
    role: str | None = None

@dataclass(slots=True)
class Model:
    capabilities: list[Capability] | None = None
    context_window: int | None = None
    created_at: str | None = None
    display_name: str | None = None
    enabled: bool | None = None
    input_cost_per_1k: float | None = None
    model_id: str | None = None
    output_cost_per_1k: float | None = None
    provider: Provider | None = None
    rid: Uuid | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class Notebook:
    created_at: str | None = None
    default_kernel: str | None = None
    description: str | None = None
    id: str | None = None
    name: str | None = None
    owner_id: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class NumericSummary:
    avg: float | None = None
    max: float | None = None
    min: float | None = None
    n: int | None = None
    sum: float | None = None

@dataclass(slots=True)
class ObjectInstance:
    created_at: str | None = None
    created_by: str | None = None
    id: str | None = None
    marking: str | None = None
    object_type_id: str | None = None
    organization_id: str | None = None
    properties: Struct | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class ObjectRef:
    display_label: str | None = None
    object_id: str | None = None
    object_type_id: Uuid | None = None
    properties_json: str | None = None

@dataclass(slots=True)
class ObjectType:
    color: str | None = None
    created_at: str | None = None
    description: str | None = None
    display_name: str | None = None
    icon: str | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    primary_key_property: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class ObjectTypeBinding:
    created_at: str | None = None
    dataset_branch: str | None = None
    dataset_id: Uuid | None = None
    dataset_version: int | None = None
    default_marking: str | None = None
    id: Uuid | None = None
    last_materialized_at: str | None = None
    last_run_status: str | None = None
    last_run_summary_json: str | None = None
    object_type_id: Uuid | None = None
    owner_id: Uuid | None = None
    preview_limit: int | None = None
    primary_key_column: str | None = None
    property_mapping: list[ObjectTypeBindingPropertyMapping] | None = None
    sync_mode: ObjectTypeBindingSyncMode | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class ObjectTypeBindingPropertyMapping:
    source_field: str | None = None
    target_property: str | None = None

@dataclass(slots=True)
class OpenTransactionRequest:
    branch: str | None = None
    media_set_rid: str | None = None

@dataclass(slots=True)
class PageRequest:
    page: int | None = None
    per_page: int | None = None

@dataclass(slots=True)
class PageResponse:
    page: int | None = None
    per_page: int | None = None
    total: int | None = None
    total_pages: int | None = None

@dataclass(slots=True)
class Path:
    edges: list[PathEdge] | None = None
    nodes: list[ObjectRef] | None = None
    weight: float | None = None

@dataclass(slots=True)
class PathEdge:
    direction: Direction | None = None
    link_type_id: Uuid | None = None

@dataclass(slots=True)
class Permission:
    action: str | None = None
    created_at: str | None = None
    description: str | None = None
    id: str | None = None
    resource: str | None = None

@dataclass(slots=True)
class Pipeline:
    compute_profile_id: str | None = None
    created_at: str | None = None
    description: str | None = None
    external: ExternalConfig | None = None
    id: Uuid | None = None
    incremental: IncrementalConfig | None = None
    lifecycle: PipelineLifecycle | None = None
    name: str | None = None
    nodes: list[PipelineNode] | None = None
    owner_id: Uuid | None = None
    project_id: Uuid | None = None
    status: str | None = None
    streaming: StreamingConfig | None = None
    type: PipelineType | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class PipelineBuildTarget:
    abort_policy: str | None = None
    build_branch: str | None = None
    force_build: bool | None = None
    job_spec_fallback: list[str] | None = None
    pipeline_rid: str | None = None

@dataclass(slots=True)
class PipelineBuilderGraphSaved:
    draft_updated_at: str | None = None
    graph_json: str | None = None
    pipeline_id: Uuid | None = None

@dataclass(slots=True)
class PipelineNode:
    config_json: str | None = None
    depends_on: list[str] | None = None
    id: str | None = None
    incremental_input: bool | None = None
    input_dataset_ids: list[Uuid] | None = None
    label: str | None = None
    output_dataset_id: Uuid | None = None
    preview_status: str | None = None
    transform_type: str | None = None
    validation_errors: list[str] | None = None
    validation_status: str | None = None

@dataclass(slots=True)
class PipelineRun:
    error_message: str | None = None
    finished_at: str | None = None
    id: Uuid | None = None
    node_results_json: str | None = None
    pipeline_id: Uuid | None = None
    started_at: str | None = None
    started_by: Uuid | None = None
    status: str | None = None

@dataclass(slots=True)
class Policy:
    action: str | None = None
    conditions: dict[str, Any] | None = None
    created_at: str | None = None
    created_by: str | None = None
    description: str | None = None
    effect: str | None = None
    enabled: bool | None = None
    id: str | None = None
    name: str | None = None
    resource: str | None = None
    row_filter: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class PolicyEvaluationResult:
    allowed: bool | None = None
    deny_policy_ids: list[str] | None = None
    matched_policy_ids: list[str] | None = None
    row_filter: str | None = None

@dataclass(slots=True)
class PresignedUrlResponse:
    expires_at: str | None = None
    headers: dict[str, str] | None = None
    url: str | None = None

@dataclass(slots=True)
class PreviewColumn:
    name: str | None = None
    type: str | None = None
    values_json: list[str] | None = None

@dataclass(slots=True)
class PreviewDataRequest:
    dataset_id: Uuid | None = None
    limit: int | None = None
    offset: int | None = None

@dataclass(slots=True)
class PreviewDataResponse:
    columns: list[Column] | None = None
    rows: list[Row] | None = None
    total_rows: int | None = None

@dataclass(slots=True)
class PreviewNextFiresRequest:
    count: int | None = None
    rid: str | None = None

@dataclass(slots=True)
class PreviewNextFiresResponse:
    fires: list[str] | None = None

@dataclass(slots=True)
class PreviewSampleColumn:
    name: str | None = None
    type: str | None = None
    values_json: list[str] | None = None

@dataclass(slots=True)
class PreviewTransformRequest:
    config_json: str | None = None
    language: TransformLanguage | None = None
    limit: int | None = None
    sample_columns: list[PreviewSampleColumn] | None = None
    source: str | None = None

@dataclass(slots=True)
class PreviewTransformResponse:
    columns: list[PreviewColumn] | None = None
    deferred: bool | None = None
    diagnostics: list[ValidationDiagnostic] | None = None
    previewed: bool | None = None
    row_count: int | None = None

@dataclass(slots=True)
class Product:
    author: str | None = None
    created_at: str | None = None
    description: str | None = None
    manifest_url: str | None = None
    name: str | None = None
    resources: list[ResourceRef] | None = None
    rid: str | None = None
    signature: str | None = None
    status: ProductStatus | None = None
    updated_at: str | None = None
    version: str | None = None

@dataclass(slots=True)
class ProductVersion:
    bundle_path: str | None = None
    manifest: str | None = None
    product_rid: str | None = None
    published_at: str | None = None
    rid: str | None = None
    signature: str | None = None
    version: str | None = None

@dataclass(slots=True)
class PromoteScenarioRequest:
    id: Uuid | None = None
    target_branch: bool | None = None

@dataclass(slots=True)
class PromoteScenarioResponse:
    action_invocation_ids: list[Uuid] | None = None

@dataclass(slots=True)
class Property:
    created_at: str | None = None
    default_value_json: str | None = None
    description: str | None = None
    display_name: str | None = None
    id: Uuid | None = None
    name: str | None = None
    object_type_id: Uuid | None = None
    property_type: str | None = None
    required: bool | None = None
    unique_constraint: bool | None = None
    updated_at: str | None = None
    validation_rules_json: str | None = None

@dataclass(slots=True)
class PropertyFilter:
    operator: str | None = None
    property_name: str | None = None
    value: Value | None = None

@dataclass(slots=True)
class PropertySort:
    direction: str | None = None
    property_name: str | None = None

@dataclass(slots=True)
class PublishRequest:
    headers: dict[str, str] | None = None
    payload: str | None = None
    schema_id: str | None = None
    topic: str | None = None

@dataclass(slots=True)
class PublishResponse:
    backend: str | None = None
    matched_pattern: str | None = None

@dataclass(slots=True)
class PublishVersionRequest:
    product_rid: str | None = None
    version: str | None = None

@dataclass(slots=True)
class QueryEventsRequest:
    action: str | None = None
    actor_id: str | None = None
    cursor: str | None = None
    from: str | None = None
    page_size: int | None = None
    resource_rid: str | None = None
    to: str | None = None

@dataclass(slots=True)
class QueryEventsResponse:
    events: list[AuditEvent] | None = None
    next_cursor: str | None = None

@dataclass(slots=True)
class QueryResult:
    columns: list[ColumnMeta] | None = None
    execution_time_ms: int | None = None
    rows: list[RowData] | None = None
    rows_scanned: int | None = None
    total_rows: int | None = None

@dataclass(slots=True)
class QueueIngestJobRequest:
    connection_id: Uuid | None = None
    max_attempts: int | None = None
    schedule_at: str | None = None
    table_name: str | None = None
    target_dataset_id: Uuid | None = None

@dataclass(slots=True)
class RecordEventRequest:
    event: AuditEvent | None = None
    raw_envelope: str | None = None

@dataclass(slots=True)
class RecordEventResponse:
    event_id: str | None = None

@dataclass(slots=True)
class RecordLineageRequest:
    node_id: str | None = None
    pipeline_id: Uuid | None = None
    source_dataset_id: Uuid | None = None
    target_dataset_id: Uuid | None = None

@dataclass(slots=True)
class RecordLineageResponse:
    pass

@dataclass(slots=True)
class RefreshRequest:
    refresh_token: str | None = None

@dataclass(slots=True)
class RegisterAccessPatternRequest:
    kind: str | None = None
    media_set_rid: str | None = None
    params: str | None = None
    persistence: PersistencePolicy | None = None
    ttl_seconds: int | None = None

@dataclass(slots=True)
class RegisterModelRequest:
    capabilities: list[Capability] | None = None
    context_window: int | None = None
    display_name: str | None = None
    enabled: bool | None = None
    input_cost_per_1k: float | None = None
    model_id: str | None = None
    output_cost_per_1k: float | None = None
    provider: Provider | None = None

@dataclass(slots=True)
class RegisterPipelineBuilderGraphRequest:
    graph_json: str | None = None
    pipeline_id: Uuid | None = None

@dataclass(slots=True)
class RegisterPythonTransformRequest:
    config_json: str | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    source: str | None = None

@dataclass(slots=True)
class RegisterRequest:
    email: str | None = None
    name: str | None = None
    password: str | None = None

@dataclass(slots=True)
class RegisterResponse:
    user_id: Uuid | None = None

@dataclass(slots=True)
class RegisterSqlTransformRequest:
    config_json: str | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    source: str | None = None

@dataclass(slots=True)
class RegisterVirtualMediaItemRequest:
    branch: str | None = None
    item_path: str | None = None
    media_set_rid: str | None = None
    mime_type: str | None = None
    physical_path: str | None = None
    sha256: str | None = None
    size_bytes: int | None = None

@dataclass(slots=True)
class ResourceMapping:
    dst_rid: str | None = None
    src_ref: str | None = None
    type: ResourceType | None = None

@dataclass(slots=True)
class ResourceRef:
    ref: str | None = None
    type: ResourceType | None = None

@dataclass(slots=True)
class ResultGroup:
    items: list[ObjectRef] | None = None
    object_type_id: Uuid | None = None
    total: int | None = None

@dataclass(slots=True)
class Role:
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None

@dataclass(slots=True)
class RoleResponse:
    created_at: str | None = None
    description: str | None = None
    id: str | None = None
    name: str | None = None
    permission_ids: list[str] | None = None
    permissions: list[str] | None = None

@dataclass(slots=True)
class Row:
    values: dict[str, str] | None = None

@dataclass(slots=True)
class RowData:
    values: list[str] | None = None

@dataclass(slots=True)
class RunAccessPatternRequest:
    access_pattern_id: str | None = None
    media_item_rid: str | None = None
    params_override: str | None = None

@dataclass(slots=True)
class RunAccessPatternResponse:
    cached: bool | None = None
    mime_type: str | None = None
    result_url: str | None = None
    size_bytes: int | None = None

@dataclass(slots=True)
class RunScheduleNowRequest:
    requested_by: str | None = None
    rid: str | None = None

@dataclass(slots=True)
class RunScheduleNowResponse:
    run_id: str | None = None

@dataclass(slots=True)
class SaveQueryRequest:
    description: str | None = None
    name: str | None = None
    sql: str | None = None

@dataclass(slots=True)
class SavedQuery:
    created_at: str | None = None
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    sql: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class Scenario:
    author_id: Uuid | None = None
    branch_context: str | None = None
    created_at: str | None = None
    description: str | None = None
    edits: list[StagedEdit] | None = None
    graph_id: Uuid | None = None
    id: Uuid | None = None
    name: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class ScenarioDiff:
    added_count: int | None = None
    changed_edge_count: int | None = None
    changed_node_count: int | None = None
    impacted_object_refs: list[str] | None = None
    metrics_json: str | None = None
    removed_count: int | None = None
    scenario_id: Uuid | None = None

@dataclass(slots=True)
class Schedule:
    created_at: str | None = None
    description: str | None = None
    last_run_at: str | None = None
    name: str | None = None
    paused: bool | None = None
    project_rid: str | None = None
    rid: str | None = None
    target: ScheduleTarget | None = None
    trigger: Trigger | None = None
    updated_at: str | None = None
    version: int | None = None

@dataclass(slots=True)
class ScheduleRun:
    build_rid: str | None = None
    failure_reason: str | None = None
    finished_at: str | None = None
    outcome: RunOutcome | None = None
    rid: str | None = None
    schedule_rid: str | None = None
    schedule_version: int | None = None
    trigger_snapshot: dict[str, str] | None = None
    triggered_at: str | None = None

@dataclass(slots=True)
class ScheduleTarget:
    dataset_build: DatasetBuildTarget | None = None
    health_check: HealthCheckTarget | None = None
    pipeline_build: PipelineBuildTarget | None = None
    sync_run: SyncRunTarget | None = None

@dataclass(slots=True)
class Schema:
    custom_metadata: CustomMetadata | None = None
    fields: list[Field] | None = None
    file_format: FileFormat | None = None

@dataclass(slots=True)
class SearchAround:
    created_at: str | None = None
    description: str | None = None
    id: Uuid | None = None
    owner_id: Uuid | None = None
    parameters: list[SearchAroundParameter] | None = None
    project_id: Uuid | None = None
    rid: str | None = None
    starting_object_type_id: Uuid | None = None
    steps: list[SearchAroundStep] | None = None
    title: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class SearchAroundFilter:
    literal_json: str | None = None
    op: FilterOp | None = None
    parameter_ref: str | None = None
    property: str | None = None

@dataclass(slots=True)
class SearchAroundParameter:
    default_value_json: str | None = None
    description: str | None = None
    name: str | None = None
    required: bool | None = None
    type: ParamType | None = None

@dataclass(slots=True)
class SearchAroundStep:
    direction: Direction | None = None
    filters: list[SearchAroundFilter] | None = None
    ordinal: int | None = None
    relation_id: Uuid | None = None

@dataclass(slots=True)
class SearchObjectsRequest:
    object_type_id: str | None = None
    pagination: PageRequest | None = None
    query: str | None = None

@dataclass(slots=True)
class SearchObjectsResponse:
    objects: list[ObjectInstance] | None = None
    pagination: PageResponse | None = None

@dataclass(slots=True)
class Session:
    created_at: str | None = None
    id: str | None = None
    kernel: str | None = None
    last_activity: str | None = None
    notebook_id: str | None = None
    started_by: str | None = None
    status: str | None = None

@dataclass(slots=True)
class StagedEdit:
    action_id: Uuid | None = None
    kind: EditKind | None = None
    new_value_json: str | None = None
    old_value_json: str | None = None
    property_name: str | None = None
    target_ref: str | None = None

@dataclass(slots=True)
class StopSessionRequest:
    session_id: str | None = None

@dataclass(slots=True)
class StreamConfig:
    checkpoint_interval_ms: int | None = None
    compression: bool | None = None
    ingest_consistency: StreamConsistency | None = None
    partitions: int | None = None
    pipeline_consistency: StreamConsistency | None = None
    retention_ms: int | None = None
    type: StreamType | None = None

@dataclass(slots=True)
class StreamingConfig:
    input_stream_id: Uuid | None = None
    output_stream_id: Uuid | None = None
    parallelism: int | None = None
    streaming_profile_id: str | None = None

@dataclass(slots=True)
class StructParams:
    sub_schemas: list[Field] | None = None

@dataclass(slots=True)
class SubscribeRequest:
    pattern: str | None = None

@dataclass(slots=True)
class SyncConnectionRequest:
    connection_id: Uuid | None = None
    table_name: str | None = None
    target_dataset_id: Uuid | None = None

@dataclass(slots=True)
class SyncRunTarget:
    source_rid: str | None = None
    sync_rid: str | None = None

@dataclass(slots=True)
class SyncStatus:
    error: str | None = None
    rows_synced: int | None = None
    status: str | None = None

@dataclass(slots=True)
class TestConnectionRequest:
    id: Uuid | None = None

@dataclass(slots=True)
class TestConnectionResponse:
    message: str | None = None
    success: bool | None = None

@dataclass(slots=True)
class TimeTrigger:
    cron: str | None = None
    flavor: CronFlavor | None = None
    time_zone: str | None = None

@dataclass(slots=True)
class Timestamps:
    created_at: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class TokenPair:
    access_token: str | None = None
    expires_in: int | None = None
    refresh_token: str | None = None

@dataclass(slots=True)
class Tool:
    description: str | None = None
    name: str | None = None
    parameters_json_schema: str | None = None

@dataclass(slots=True)
class Transaction:
    branch: str | None = None
    closed_at: str | None = None
    media_set_rid: str | None = None
    opened_at: str | None = None
    opened_by: str | None = None
    rid: str | None = None
    state: TransactionState | None = None

@dataclass(slots=True)
class Transform:
    config_json: str | None = None
    created_at: str | None = None
    id: Uuid | None = None
    language: TransformLanguage | None = None
    name: str | None = None
    owner_id: Uuid | None = None
    source: str | None = None
    updated_at: str | None = None

@dataclass(slots=True)
class TraverseLinksRequest:
    depth: int | None = None
    direction: LinkDirection | None = None
    limit: int | None = None
    link_type_api_name: str | None = None
    link_type_api_names: list[str] | None = None
    object_type_id: str | None = None
    primary_key: str | None = None

@dataclass(slots=True)
class TraverseLinksResponse:
    edges: list[LinkedEdge] | None = None
    objects: list[ObjectInstance] | None = None

@dataclass(slots=True)
class Trigger:
    compound: CompoundTrigger | None = None
    event: EventTrigger | None = None
    time: TimeTrigger | None = None

@dataclass(slots=True)
class TriggerRunRequest:
    pipeline_id: Uuid | None = None

@dataclass(slots=True)
class UnbindDatasetRequest:
    binding_id: Uuid | None = None
    object_type_id: Uuid | None = None

@dataclass(slots=True)
class UnbindDatasetResponse:
    deleted: bool | None = None

@dataclass(slots=True)
class UninstallRequest:
    installation_rid: str | None = None

@dataclass(slots=True)
class UpdateAnnotationRequest:
    geometry_json: str | None = None
    id: Uuid | None = None
    text: str | None = None

@dataclass(slots=True)
class UpdateCellRequest:
    cell_id: str | None = None
    cell_type: str | None = None
    kernel: str | None = None
    position: int | None = None
    source: str | None = None

@dataclass(slots=True)
class UpdateControlPanelRequest:
    allow_self_signup: bool | None = None
    allowed_email_domains: list[str] | None = None
    announcement_banner: str | None = None
    default_app_branding: AppBrandingSettings | None = None
    default_region: str | None = None
    deployment_mode: str | None = None
    docs_url: str | None = None
    maintenance_mode: bool | None = None
    platform_name: str | None = None
    release_channel: str | None = None
    restricted_operations: list[str] | None = None
    status_page_url: str | None = None
    support_email: str | None = None

@dataclass(slots=True)
class UpdateDatasetRequest:
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None
    tags: list[str] | None = None

@dataclass(slots=True)
class UpdateGraphRequest:
    branch_context: str | None = None
    description: str | None = None
    id: Uuid | None = None
    layer_configuration_json: str | None = None
    layout_state_json: str | None = None
    model_rid: str | None = None
    seed_object_refs: list[str] | None = None
    timeline_state_json: str | None = None
    title: str | None = None

@dataclass(slots=True)
class UpdateGroupRequest:
    description: str | None = None
    role_ids: list[str] | None = None

@dataclass(slots=True)
class UpdateNotebookRequest:
    default_kernel: str | None = None
    description: str | None = None
    id: str | None = None
    name: str | None = None

@dataclass(slots=True)
class UpdateObjectRequest:
    marking: str | None = None
    object_type_id: str | None = None
    primary_key: str | None = None
    properties: Struct | None = None
    replace: bool | None = None

@dataclass(slots=True)
class UpdateObjectTypeRequest:
    color: str | None = None
    description: str | None = None
    display_name: str | None = None
    icon: str | None = None
    id: Uuid | None = None
    primary_key_property: str | None = None

@dataclass(slots=True)
class UpdatePipelineRequest:
    description: str | None = None
    id: Uuid | None = None
    name: str | None = None
    nodes: list[PipelineNode] | None = None

@dataclass(slots=True)
class UpdateRoleRequest:
    description: str | None = None
    permission_ids: list[str] | None = None

@dataclass(slots=True)
class UpdateScenarioRequest:
    description: str | None = None
    edits: list[StagedEdit] | None = None
    id: Uuid | None = None
    name: str | None = None

@dataclass(slots=True)
class UpdateScheduleRequest:
    change_comment: str | None = None
    description: str | None = None
    edited_by: str | None = None
    name: str | None = None
    paused: bool | None = None
    rid: str | None = None
    target: ScheduleTarget | None = None
    trigger: Trigger | None = None

@dataclass(slots=True)
class UpdateSearchAroundRequest:
    description: str | None = None
    id: Uuid | None = None
    parameters: list[SearchAroundParameter] | None = None
    steps: list[SearchAroundStep] | None = None
    title: str | None = None

@dataclass(slots=True)
class UpdateUserRequest:
    attributes: dict[str, Any] | None = None
    is_active: bool | None = None
    mfa_enforced: bool | None = None
    name: str | None = None
    organization_id: str | None = None

@dataclass(slots=True)
class UpsertPolicyRequest:
    action: str | None = None
    conditions: dict[str, Any] | None = None
    description: str | None = None
    effect: str | None = None
    enabled: bool | None = None
    name: str | None = None
    resource: str | None = None
    row_filter: str | None = None

@dataclass(slots=True)
class Usage:
    completion_tokens: int | None = None
    prompt_tokens: int | None = None
    total_tokens: int | None = None

@dataclass(slots=True)
class UserInfo:
    email: str | None = None
    id: Uuid | None = None
    name: str | None = None
    roles: list[str] | None = None

@dataclass(slots=True)
class UserResponse:
    attributes: dict[str, Any] | None = None
    auth_source: str | None = None
    created_at: str | None = None
    email: str | None = None
    groups: list[str] | None = None
    id: str | None = None
    is_active: bool | None = None
    mfa_enabled: bool | None = None
    mfa_enforced: bool | None = None
    name: str | None = None
    organization_id: str | None = None
    permissions: list[str] | None = None
    roles: list[str] | None = None

@dataclass(slots=True)
class Uuid:
    value: str | None = None

@dataclass(slots=True)
class ValidateTransformRequest:
    config_json: str | None = None
    language: TransformLanguage | None = None
    source: str | None = None

@dataclass(slots=True)
class ValidateTransformResponse:
    diagnostics: list[ValidationDiagnostic] | None = None
    valid: bool | None = None

@dataclass(slots=True)
class ValidationDiagnostic:
    code: str | None = None
    column: int | None = None
    line: int | None = None
    message: str | None = None
    severity: ValidationSeverity | None = None

@dataclass(slots=True)
class WatchIngestJobRequest:
    id: Uuid | None = None
    poll_interval_ms: int | None = None
